version: 2

models:
  - name: tips_change_with_time
    description: "Aggregated dataset tracking the sum of tips and percentage change over time for top taxi drivers."
    columns:
      - name: taxi_id
        data_type: string
        description: "Unique identifier for the taxi."

      - name: year_month
        data_type: string
        description: "Year and month of the recorded data in YYYY-MM format."

      - name: tips_sum
        data_type: float64
        description: "Total sum of tips received by the taxi in the given month."

      - name: tips_change
        data_type: float64
        description: "Percentage change in tips compared to the previous month."

  - name: top_three_cars
    description: "Identifies the top three taxi drivers who received the highest sum of tips in April 2018."
    columns:
      - name: taxi_id
        data_type: string
        description: "Unique identifier for the taxi."
